name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --workspaces --if-present

      - name: Build
        run: npm run build --workspaces --if-present

      - name: Test
        env:
          CI: true
        run: npm test --workspaces --if-present -- --coverage --watch=false

      - name: Enforce Coverage >= 80%
        run: |
          node -e "const fs=require('fs');
          const p=['coverage/coverage-summary.json','coverage/combined-summary.json'].find(fs.existsSync);
          if(!p){console.error('No coverage summary found');process.exit(1)}
          const s=JSON.parse(fs.readFileSync(p,'utf8'));
          const pct=(s.total.lines.pct||s.total.lines.covered*100/s.total.lines.total);
          if(pct<80){console.error('Coverage below 80%:',pct);process.exit(1)}
          console.log('Coverage OK:',pct)" 

      - name: Deploy
        if: github.ref == 'refs/heads/main' && success()
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          echo "Deploying with env-only secrets..."
          # insert deploy command using $DEPLOY_TOKEN and environment config

      - name: Smoke Tests
        if: github.ref == 'refs/heads/main' && success()
        run: npm run smoke --workspaces --if-present

      - name: Rollback if Smoke Fails
        if: github.ref == 'refs/heads/main' && failure()
        run: |
          echo "Smoke tests failed; initiating rollback..."
          # insert rollback command


